# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

logger:
  default: warning

# Text to speech
tts:
  - platform: google_translate

duckdns:
  domain: !secret dns_domain
  access_token: !secret dns_token

# Needed to turn on TV
wake_on_lan:

# TV
webostv:
  - name: Living Room TV
    host: !secret ip_living_room_tv
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret mac_living_room_tv

alarm_control_panel:
  - platform: alarmdotcom
    username: !secret alarm_username
    password: !secret alarm_password

notify:
  - name: Slack
    platform: slack
    api_key: !secret notify_slack_api_key
    default_channel: "#home-events"

input_text:
  slack_verification_token:
    initial: !secret slack_verification_token

rest_command: !include_dir_named rest_command

switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      rf_plug_1:
        pulselength: 417
        code_on: 1381717
        code_off: 1381716
      rf_plug_2:
        pulselength: 417
        code_on: 1394005
        code_off: 1394004
      rf_plug_3:
        pulselength: 417
        code_on: 1397077
        code_off: 1397076
      rf_plug_4:
        pulselength: 417
        code_on: 1397845
        code_off: 1397844

template:
  - sensor:
      - name: Someone Home Probability
        unit_of_measurement: '%'
        state: '{{ state_attr("binary_sensor.someone_home", "probability") }}'
      - name: Someone Home Probability Threshold
        unit_of_measurement: '%'
        state: '{{ state_attr("binary_sensor.someone_home", "probability_threshold") }}'

binary_sensor:
  - platform: bayesian
    name: Someone Home
    prior: 0.7
    probability_threshold: 0.9
    observations:
      - entity_id: group.chris_emilia
        platform: state
        to_state: home
        prob_given_true: 0.96
        prob_given_false: 0.01
      - entity_id: group.chris_emilia
        platform: state
        to_state: not_home
        prob_given_true: 0.04
        prob_given_false: 0.99
      - entity_id: binary_sensor.edgeos_device_lgwebostv
        platform: state
        to_state: on
        prob_given_true: 0.25
        prob_given_false: 0
      - entity_id: binary_sensor.edgeos_device_lgwebostv
        platform: state
        to_state: off
        prob_given_true: 0.75
        prob_given_false: 1
      - entity_id: group.living_room_lights
        platform: state
        to_state: on
        prob_given_true: 0.4
        prob_given_false: 0.01
      - entity_id: group.living_room_lights
        platform: state
        to_state: off
        prob_given_true: 0.6
        prob_given_false: 0.99


frontend:
  themes: !include_dir_merge_named themes
automation: !include_dir_list automation
group: !include_dir_named group
script: !include_dir_named script
scene: !include scenes.yaml
recorder: !include recorder.yaml
