# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  name: !secret home_name
  internal_url: !secret hass_internal_url
  external_url: !secret hass_external_url
  country: GB

google_assistant: !include google_assistant/configuration.yaml

http:
  server_port: 443
  ssl_key: !secret hass_ssl_key
  ssl_certificate: !secret hass_ssl_certificate
  use_x_forwarded_for: true
  # https://www.cloudflare.com/ips-v4/
  trusted_proxies:
    - 127.0.0.1
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22

logger:
  default: warning

# Enable bluetooth integration
bluetooth:

# Text to speech
tts:
  - platform: google_translate

duckdns:
  domain: !secret dns_domain
  access_token: !secret dns_token

# Needed to turn on TV
wake_on_lan:

# Cameras
ffmpeg:
camera: !include_dir_list camera

input_text:
  slack_verification_token:
    initial: !secret slack_verification_token
    mode: password
  hass_internal_url:
    initial: !secret hass_internal_url
    mode: password

rest_command: !include_dir_named rest_command
switch: !include_dir_list switch
template: !include_dir_list template
binary_sensor: !include_dir_list binary_sensor
sensor: !include_dir_list sensor
command_line: !include_dir_list command_line
frontend:
  themes: !include_dir_merge_named themes
automation: !include_dir_list automation
group: !include_dir_named group
script: !include_dir_named script
scene: !include scenes.yaml
shell_command: !include_dir_named shell_command
recorder: !include recorder.yaml
