id: inkbird_low_battery
alias: Inkbird - Low Battery
trigger:
- platform: numeric_state
  entity_id:
  - sensor.ibs_th2_p01b_1a4c_battery
  - sensor.ibs_th2_p01b_1ab3_battery
  below: 11
  for:
    minutes: 5
condition: '{{ (as_timestamp(now()) - as_timestamp(this.attributes.last_triggered)) | int(0) > 86400 }}'
action:
- service: notify.slack
  data:
    message: ':low_battery: {{ trigger.to_state.name }} at {{ trigger.to_state.state }}%.'
- service: todoist.new_task
  data:
    project: House 🏡
    content: Replace {{ trigger.to_state.name }} battery
    assignee: Chris
    priority: 3
    due_date_string: today
    due_date_lang: en
mode: queued
max: 10
