id: presence_noone_home
alias: Presence - No One is Home
trigger:
- platform: state
  entity_id: binary_sensor.someone_home
  to: 'off'
  for:
    minutes: 6
action:
- service: script.leaving_home
mode: single
