id: presence_waitrose
alias: Presence - Arriving at Waitrose
mode: single
trigger:
- platform: zone
  entity_id:
  - device_tracker.chriss_iphone
  - device_tracker.iphone_13_pro_3
  zone: zone.waitrose
  event: enter

condition:
- condition: numeric_state
  entity_id: todo.shopping_list
  above: 0
- condition: state
  alias: Waitrose is open
  entity_id: schedule.waitrose_opening_hours
  state: 'on'
- condition: template
  alias: Automation hasn't triggered in 2 hours
  value_template: "{{ now() - this.attributes.last_triggered > timedelta(hours=2) }}"
- condition: template
  alias: User isn't driving
  value_template: >
    {% set sensor = 'sensor.{0}_activity'.format(trigger.entity_id | replace('device_tracker.', '')) %}
    {{ states(sensor) != 'Automotive' }}

action:
- action: "notify.mobile_app_{{ trigger.entity_id | replace('device_tracker.', '') }}"
  data:
    title: Shopping List
    message: >
      There {% if states('todo.shopping_list') | int < 2 -%}
        is 1 item
      {%- else -%}
        are {{ states('todo.shopping_list') }} items
      {%- endif %} on your shopping list.
    data:
      url: /todo/shopping_list
