id: presence_working_location
alias: Presence - Working Location
description: >
  Notifies if a working location is not set for tomorrow.
mode: single

trigger:
- platform: time
  at: '21:00:00'

condition:
- condition: state
  entity_id: binary_sensor.working_day_tomorrow
  state: 'on'

action:
- action: calendar.get_events
  target:
    entity_id: calendar.working_locations
  data:
    start_date_time: "{{ today_at() + timedelta(days=1) }}"
    duration:
      days: 1
  response_variable: calendars
- if:
  - condition: template
    alias: Tomorrow's working location not set
    value_template: |
      {{ calendars[calendars | first].events | length == 0 }}
  then:
  - action: notify.mobile_app_chriss_iphone
    data:
      message: '🗓️ Have you set tomorrow’s working location?'
      data:
        url: |
          {% set urlformat = 'https://calendar.google.com/calendar/u/0/r/day/%Y/%-m/%-d' %}
          {{ (now() + timedelta(days=1)) | as_timestamp | timestamp_custom(urlformat) }}
