sensor:
  name: Next Bin Date
  unique_id: next_bin_date
  command: |
    sort -k2 /config/shell_command/download_bin_schedule.txt | head -1 | jq -MR 'split(" ") | {type: .[0], date: .[1]}'
  value_template: "{{ value_json.date }}"
  json_attributes:
    - type
