version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./ha:/config:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/ssl:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/gpiomem
    restart: unless-stopped
