unique_id: ssl_cert_expiry_homeassistant
trigger:
- platform: time
  at: '04:10:00'
action:
- service: shell_command.monitor_cloudflare_origin
  response_variable: monitor
  data:
    domain: "{{ states('input_text.hass_internal_url') | replace('https://', '') }}"
    token: !secret cloudflare_origin_token
    record_type: AAAA
sensor:
- unique_id: ssl_cert_expiry_timestamp_homeassistant
  name: "{{ states('input_text.hass_internal_url') | replace('https://', '') }} Cert expiry"
  icon: mdi:certificate
  device_class: timestamp
  state: "{{ monitor['stdout'] }}"
  availability: "{{ monitor['stdout'] | length > 0 }}"
  attributes:
    is_valid: "{{ monitor['returncode'] == 0 }}"
    error: "{{ monitor['stderr'] }}"
