id: bins_download_schedule
alias: Bins - Download Schedule
trigger:
- platform: time
  at: '11:30:00'
condition:
- condition: time
  weekday:
  - sun
  - mon
  - tue
action:
- service: shell_command.download_bin_schedule
