id: bins_notification
alias: Bins - Notification
trigger:
- platform: time
  at: '18:30:00'
condition:
- condition: numeric_state
  entity_id: sensor.next_bin
  value_template: >
    {{ ((as_timestamp(state_attr('sensor.next_bin', 'date'), 0) - as_timestamp(now())) / 86400) }}
  below: 1
action:
- service: notify.slack
  data:
    message: >
      {%- set type = states('sensor.next_bin') -%}
      {%- if type == "GREEN" -%} :recycle:
      {%- elif type == "BLACK" -%} :wastebasket:
      {%- elif type == "BROWN" -%} :fallen_leaf:
      {%- endif %}
      {{ type[0] }}{{ type[1:] | lower }} bin is due to be collected.
