id: ssl_update_printer_certificate
alias: SSL Update - Printer
trigger:
- platform: time
  at: '04:20:00'
condition:
- condition: time
  weekday: sun
action:
- service: shell_command.update_printer_certificate
