id: ssl_update_printer_certificate
alias: SSL Update - Printer
trigger:
- platform: time
  at: '04:20:00'
condition:
- condition: template
  value_template: '{{ now().day == 1 }}'
action:
- service: shell_command.update_printer_certificate
