id: slack_inbound_webhook
alias: Slack - Inbound Webhook
trigger:
- platform: webhook
  webhook_id: slack_interactivity
  local_only: false
condition:
- condition: template
  value_template: >
    {%- set payload = trigger.data.payload | from_json -%}

    {# ephemeral messages don't send their payload with a block_actions payload #}
    {%- set action = {} -%}
    {%- if payload.message -%}
      {%- set actions = payload.message.blocks | selectattr('type', 'equalto', 'actions') | first -%}
      {%- set action = actions.elements | selectattr('action_id', 'equalto', payload.actions[0].action_id) | first -%}
    {%- endif -%}

    {# we get a callback for all block actions, even if the action is a URL button. Ignore those cases #}
    {{ (payload.token == states('input_text.slack_verification_token')) and (payload.type == 'block_actions') and ('url' not in action) }}
action:
- if:
  - condition: template
    value_template: >
      {%- set payload = trigger.data.payload | from_json -%}
      {%- set script = payload.actions[0].block_id.split('|')[0] -%}
      {{ states('script.slack_callback_' ~ script) == 'unknown' }}
  then:
  - service: system_log.write
    data_template:
      message: 'Unexpected Slack callback: {{ trigger.data.payload }}'
- service_template: >
    {%- set payload = trigger.data.payload | from_json -%}
    script.slack_callback_{{ payload.actions[0].block_id.split('|')[0] }}
  data_template:
    payload: '{{ trigger.data.payload | from_json }}'
