id: tado_low_battery
alias: Tado - Low TRV Battery
mode: parallel
trigger:
  platform: state
  entity_id:
  - binary_sensor.su4133430528_battery_state
  - binary_sensor.va0137307904_battery_state
  - binary_sensor.va1204299520_battery_state
  - binary_sensor.va2613651200_battery_state
  - binary_sensor.va3016304384_battery_state
  - binary_sensor.va3469289216_battery_state
  - binary_sensor.va3962447616_battery_state
  - binary_sensor.va4214105856_battery_state
  - binary_sensor.va4247660288_battery_state
  to: 'on'
action:
- service: notify.slack
  data_template:
    message: ":low_battery: {{ trigger.to_state.name | replace(' state', '') }} is low."
- service: todoist.new_task
  data:
    project: House 🏡
    section: "{{ area_name(trigger.entity_id) }}"
    content: Replace {{ trigger.to_state.name | replace(' state', '') }}
    description: Requires 2 × AA batteries
    assignee: Chris
    priority: 3
    due_date_string: today
    due_date_lang: en
