id: tado_temperature_office
alias: Tado - Office Temperature
description: >
  Sets the office temperature when working from home.
mode: single

trigger:
- platform: time
  at: '08:30:00'

action:
- action: calendar.get_events
  target:
    entity_id: calendar.working_locations
  data:
    duration: 0
  response_variable: calendars
- if:
  - condition: template
    alias: Working from home today
    value_template: |-
      {% set events = calendars[calendars | first].events %}
      {{ events | length == 1 and events[0].summary == 'Home' }}
  then:
  - action: tado.set_climate_timer
    target:
      entity_id: climate.office
    data:
      temperature: 19
      time_period: '08:00:00'
