id: transmission_completed_torrent
alias: Transmission - Completed Torrent
trigger:
  platform: event
  event_type: transmission_downloaded_torrent
action:
  - service: notify.slack
    data:
      message: 'Download completed: “*{{ trigger.event.data.name }}*”'
      target: '#synology'
      data:
        blocks:
        - type: section
          text:
            type: mrkdwn
            text: 'Download completed: “*{{ trigger.event.data.name }}*”'
        - type: actions
          block_id: remove_torrent
          elements:
          - type: button
            style: primary
            text:
              type: plain_text
              text: Remove Torrent
            action_id: remove_torrent
            value: 'id:{{ trigger.event.data.id }}'
