id: doorbell_ring
alias: Doorbell - Ring
trigger:
- platform: state
  entity_id: binary_sensor.front_door_ding
  to: 'on'
action:
- service: notify.slack
  data:
    message: ':bell: Someone is at your front door.'
- condition: state
  entity_id: binary_sensor.someone_home
  state: 'on'
- service: media_player.play_media
  data_template:
    media_content_id: >
      {{ states('input_text.hass_internal_url') }}/local/doorbell_tones/ring.mp3
    media_content_type: music
  entity_id: media_player.all
mode: single
