id: ha_new_version_available
alias: Home Assistant - New Version Available
trigger:
  platform: state
  entity_id: sensor.ha_latest_version
condition:
- condition: template
  value_template: >
    {{ states('sensor.ha_current_version') != states('sensor.ha_latest_version') }}
action:
- service: persistent_notification.create
  data_template:
    title: New Version Available
    message: >
      Home Assistant version {{ states('sensor.ha_latest_version') }} is now available.
    notification_id: ha_new_version_available
