homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
  user: homeassistant
  password: '!secrets.yaml password'
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
